### ISSUE TITLE
Correct links for "Virtual Student Federal Service: my UX apprenticeship journey"

### ISSUE THREAD

**Issue by daniel-coleman-1** [ONRR/blog-nrrd#103]
https://blog-nrrd.doi.gov/intern-onrr-dot-gov/

Link text "Explore Data Feature" in paragraph 2
Link text "lo-fidelity wireframes" in paragraph titled "Prototyping"

**Comment by daniel-coleman-1** [comment]
![Screenshot 2021-11-01 102305](https://user-images.githubusercontent.com/83892362/139706490-655e8703-8c9e-417f-b9ec-0e7c34b21a92.png)
![Screenshot 2021-11-01 102246](https://user-images.githubusercontent.com/83892362/139706494-daaa28e6-4d3c-4f57-abb3-b0a7fa97222a.png)
![Screenshot 2021-11-01 102150](https://user-images.githubusercontent.com/83892362/139706531-1045d2da-95a5-40fb-a841-73e02a42089d.png)

**Comment by mcharg** [comment]
@daniel-coleman-1 I'll reach out to @persam2 on this one to see if she can get us screenshots of the prototype in place of the links.

**Comment by mcharg** [comment]
@persam2 is looking for the source files on an external hard drive.

**Comment by mcharg** [comment]
This is fixed.
