### ISSUE TITLE
Correct link for "Re-evaluating how we work: bringing the whole team along"

### ISSUE THREAD

**Issue by daniel-coleman-1** [ONRR/blog-nrrd#104]
Link text "soft launch" in paragraph "Final deliverable"

**Comment by daniel-coleman-1** [comment]
![Screenshot 2021-11-01 103240](https://user-images.githubusercontent.com/83892362/139706965-15d4d693-90e9-4be1-8315-96242e9ad397.png)

**Comment by daniel-coleman-1** [comment]
![Screenshot 2021-11-01 103458](https://user-images.githubusercontent.com/83892362/139707057-741b8151-44f0-4a1c-b075-6f47fd11a8cc.png)

**Comment by mcharg** [comment]
@daniel-coleman-1 I think we should just remove this link, since the site's no longer out there.

**Comment by mcharg** [comment]
This is fixed.
