### ISSUE TITLE
Correct Links for "How to effectively champion a government product"

### ISSUE THREAD

**Issue by daniel-coleman-1** [ONRR/blog-nrrd#105]
https://blog-nrrd.doi.gov/product-champion/

Link text "President’s Management Agenda Cross-Agency Priority (CAP) goals"
![Screenshot 2021-11-02 095136](https://user-images.githubusercontent.com/83892362/139886009-5a1e0c15-db03-4d17-bff0-946bb38d1a45.png)

**Comment by mcharg** [comment]
@daniel-coleman-1 Correct link: https://trumpadministration.archives.performance.gov/CAP/overview/

**Comment by mcharg** [comment]
This is fixed.
