### ISSUE TITLE
Revisit Links for "Beyond open data"

### ISSUE THREAD

**Issue by daniel-coleman-1** [ONRR/blog-nrrd#106]
https://blog-nrrd.doi.gov/beyond-open-data/

Links aren't broken, but may want to be revisited for clarity around repository "ONRR/doi-extractives-data"
"

**Comment by mcharg** [comment]
@daniel-coleman-1 Missing a bracket.
![image](https://user-images.githubusercontent.com/38465926/143269206-20a24d0b-393f-40f2-9ee5-d908de1501d7.png)

**Comment by daniel-coleman-1** [comment]
@mcharg links updated in dev:
https://dev-blog-nrrd.app.cloud.gov/beyond-open-data/

**Comment by mcharg** [comment]
This is fixed.
