### ISSUE TITLE
Correct Link for "Making open data useful"

### ISSUE THREAD

**Issue by daniel-coleman-1** [ONRR/blog-nrrd#107]
https://blog-nrrd.doi.gov/open-data-useful/

Link text "Filterable tables"

![Screenshot 2021-11-02 100302](https://user-images.githubusercontent.com/83892362/139893836-8ca203f5-1a62-4b43-b579-dec487e0cab6.png)

**Comment by mcharg** [comment]
@jlouis-onrr Can we set up a redirect from this page to the query tool?  It was the query tool before the redesign.
https://revenuedata.doi.gov/explore/revenue/

**Comment by mcharg** [comment]
I created #1821 to create a redirect.

**Comment by Maroyafaied** [comment]
Taken care of with PR for #1821.
