### ISSUE TITLE
Correct link for "Teaching digital skills: learning usability testing by peer training"

### ISSUE THREAD

**Issue by daniel-coleman-1** [ONRR/blog-nrrd#108]
https://blog-nrrd.doi.gov/usability-testing-training/

Link text "A Practical Guide to Usability Testing"

![Screenshot 2021-11-02 102030](https://user-images.githubusercontent.com/83892362/139904863-44478f18-ba0e-4a84-b84f-9337981fb34f.png)

**Comment by mcharg** [comment]
@daniel-coleman-1 Correct link: https://redish.net/books/usability-testing/

**Comment by mcharg** [comment]
@daniel-coleman-1 This one didn't get updated.

**Comment by daniel-coleman-1** [comment]
@mcharg links updated in the open PR:
https://dev-blog-nrrd.app.cloud.gov/usability-testing-training/

**Comment by mcharg** [comment]
This is fixed.
