### ISSUE TITLE
Correct Links for "Building technical capacity with team members"

### ISSUE THREAD

**Issue by daniel-coleman-1** [ONRR/blog-nrrd#109]
https://blog-nrrd.doi.gov/building-technical-with-team-members/

Link text
"Revenue table"
"Revenue"
"Production downloads"

![Screenshot 2021-11-02 102354](https://user-images.githubusercontent.com/83892362/139905238-7efbd4d1-75fc-4f49-a7e2-c8b5e7ed22ae.png)

**Comment by mcharg** [comment]
These should all be fixed with redirects.  See #1821.

**Comment by Maroyafaied** [comment]
Taken care of with PR for #1821.
