### ISSUE TITLE
Write blog post about cross training experience - Cat

### ISSUE THREAD

**Issue by cvojslavek** [ONRR/blog-nrrd#114]

**Comment by cvojslavek** [comment]
Hi @Maroyafaied @lpgoldstein @mcharg @cthomasONRR @daniel-coleman-1 @codyeckstein, if you have time can you please review my [draft blog post](https://teams.microsoft.com/l/file/98C68007-4312-4D55-9271-309827F6FC54?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=docx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FBlog%2FBlog-Post-CV-ForReview.docx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a)? Please feel free to edit and give feedback! Thank you.

**Comment by Maroyafaied** [comment]
@cvojslavek  I just read it without editing, I love how you captured quotes for team members and it's awesome hearing about our team from your perspective! I'll read it again and make edits later today or tomorrow.
