### ISSUE TITLE
Blog post about 508 compliance stakeholder interviews

### ISSUE THREAD

**Issue by mcharg** [ONRR/blog-nrrd#116]
I think other agencies would benefit from our learning.

**Comment by mcharg** [comment]
@lpgoldstein @cthomasONRR Do either of you want to work on this?

**Comment by lpgoldstein** [comment]
@mcharg yes

**Comment by cthomasONRR** [comment]
@mcharg Sure! @lpgoldstein do you want to co-work on this one?

**Comment by cthomasONRR** [comment]
I started drafting a blog post [here](https://teams.microsoft.com/l/file/3266514F-38F0-406A-A9E6-86FC1C693059?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=docx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FBlog%2F508_Compliance_Study.docx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a)

**Comment by cthomasONRR** [comment]
@lpgoldstein I have a rough draft ready for your review/additions. I mainly took content from our powerpoint presentation. I omitted info about ONRR Resource, but kept everything else. Please feel free to change whatever you want, and let me know if you would like to discuss. Thanks!

**Comment by cthomasONRR** [comment]
@Maroyafaied @mcharg @daniel-coleman-1 This blog post is ready for your review!

**Comment by mcharg** [comment]
@cthomasONRR @lpgoldstein Looks good.  I made a few comments and edits in the doc.

**Comment by Maroyafaied** [comment]
@cthomasONRR @lpgoldstein I have reviewed and made comments/edits, looks good overall!

**Comment by cthomasONRR** [comment]
@daniel-coleman-1 Could you review the blog post?

**Comment by daniel-coleman-1** [comment]
@cthomasONRR gave it a read yesterday and will add notes later today.  Looks good!!

**Comment by cthomasONRR** [comment]
I added in the following GitHub reference:  https://github.com/ONRR/research/tree/master/onnr-dot-gov-research/09_508_Study

**Comment by daniel-coleman-1** [comment]
@cthomasONRR I added some edits - very minor, it's an excellent piece!

**Comment by cthomasONRR** [comment]
Thanks! I resolved all comments/edits and this is ready to be put in markdown.
