### ISSUE TITLE
Blog post about troubleshooting wizard

### ISSUE THREAD

**Issue by mcharg** [ONRR/blog-nrrd#117]
When we finish it, we should write a blog post.

**Comment by codyeckstein** [comment]
I was thinking about this last night.

**Comment by mcharg** [comment]
Met with Cody and he's going to add his parts as he has time.

**Comment by mcharg** [comment]
@codyeckstein said he should have time to work on his part this week.

**Comment by mcharg** [comment]
@Maroyafaied @cthomasONRR @lpgoldstein This is ready for you to review.
https://doimspp.sharepoint.com/:w:/r/sites/NRRD/Shared%20Documents/General/Blog/In%20Progress/Troubleshooting.docx?d=wdf7cc2e8094d44349bc752b7c8ce6c05&csf=1&web=1&e=VOkwrz

**Comment by cthomasONRR** [comment]
@mcharg Looks amazing! I added a few comments. Thanks for your work on this!

**Comment by lpgoldstein** [comment]
@mcharg This looks great. I left comments/edits in doc. Thanks for always taking the time to reflect on our work and how we can do more and be better.

**Comment by mcharg** [comment]
I addressed comments, added alt text, and made tweaks to reduce the reading level from grade 10 to grade 9, if anyone wants to take another read through.

**Comment by cthomasONRR** [comment]
@mcharg Looks good, thanks for addressing the comments!
