### ISSUE TITLE
Write a blog post about making the org chart accessible beyond the auto checks

### ISSUE THREAD

**Issue by mcharg** [ONRR/blog-nrrd#133]
Both Christina and Sid will be collaborating with me.

**Comment by mcharg** [comment]
@Maroyafaied @lpgoldstein @cthomasONRR This is ready for you to review.
https://doimspp-my.sharepoint.com/:w:/r/personal/mchargs_mms_gov/Documents/NRRD%20Portal/Outreach/Blog/GettingBeyondAutoChecks.docx?d=we6790b2482144699861d878af9c12285&csf=1&web=1&e=ZsZPM1

**Comment by cthomasONRR** [comment]
@mcharg I added some comments and made some grammar/wording revisions.

**Comment by Maroyafaied** [comment]
@mcharg looks great, I only had title suggestions that I added a comment for. Thanks

**Comment by lpgoldstein** [comment]
@mcharg Have we ever thought about doing an alternate org chart that is listed as you have in the alt text? I found that so much easier to read than the boxes. In less than 5 minutes, I have a better understanding of ONRR organization than I ever have before!

**Comment by mcharg** [comment]
@lpgoldstein You mean on a page?

**Comment by lpgoldstein** [comment]
Yes or locked word?

**Comment by mcharg** [comment]
Something to think about in the future.
