### ISSUE TITLE
February analytics

### ISSUE THREAD

**Issue by mcharg** [ONRR/blog-nrrd#134]

**Comment by mcharg** [comment]
@daniel-coleman-1 Before you get started on this, I moved the blog analytics folder over to Teams. I updated the links to the spreadsheet in the instructions on the wiki.

New folder location (limited access): https://doimspp.sharepoint.com/:f:/r/sites/NRRD/Shared%20Documents/General/Blog/Blog%20Analytics?csf=1&web=1&e=t9Y1yr

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 I'm reassigning this to @mcharg since she did most of the work today during the meeting and will finish showing you tomorrow. Next month, I'll assign the analytics to you.

**Comment by mcharg** [comment]
Done. https://github.com/ONRR/blog-nrrd/wiki/Analytics
