### ISSUE TITLE
Agile blog post

### ISSUE THREAD

**Issue by mcharg** [ONRR/blog-nrrd#149]

**Comment by mcharg** [comment]
@Maroyafaied @cthomasONRR This is ready for you to review. https://doimspp.sharepoint.com/:w:/r/sites/NRRD/Shared%20Documents/General/Blog/In%20Progress/Agile.docx?d=w04465ddb478d4b48bd6dc5654cdb9e22&csf=1&web=1&e=uGBD2m

**Comment by Maroyafaied** [comment]
@mcharg looks good, added one comment.

**Comment by mcharg** [comment]
@Maroyafaied @cthomasONRR Comments addressed, if you want to take another look.

**Comment by cthomasONRR** [comment]
@mcharg Thanks, looks good

**Comment by mcharg** [comment]
@lpgoldstein @Maroyafaied This is ready to review in a PR. https://github.com/ONRR/blog-nrrd/pull/159
