### ISSUE TITLE
Write final blog post (for now)

### ISSUE THREAD

**Issue by mcharg** [ONRR/blog-nrrd#150]

**Comment by mcharg** [comment]
@lpgoldstein @Maroyafaied @cthomasONRR This is ready to review.
https://doimspp.sharepoint.com/:w:/r/sites/NRRD/Shared%20Documents/General/Blog/In%20Progress/PassingBaton.docx?d=wedf1f874d4934ea5a45acd50d01c2f6a&csf=1&web=1&e=vSOsot

**Comment by cthomasONRR** [comment]
@mcharg Thanks, looks good

**Comment by Maroyafaied** [comment]
@mcharg looks great.

**Comment by mcharg** [comment]
This is waiting in a PR.  Once we merge the agile post to dev, we can get a preview and QA.
https://github.com/ONRR/blog-nrrd/pull/160

**Comment by mcharg** [comment]
@Maroyafaied This is just waiting for your approval on the PR.  But don't merge it until the agile post goes live.
