### ISSUE TITLE
CX blog post

### ISSUE THREAD

**Issue by mcharg** [ONRR/blog-nrrd#151]

**Comment by mcharg** [comment]
@lpgoldstein @Maroyafaied @cthomasONRR 
Draft is ready to review before putting into markdown.
https://doimspp.sharepoint.com/:w:/r/sites/NRRD/Shared%20Documents/General/Blog/In%20Progress/CX.docx?d=wa22ade69ee0a414ea5adad00ecd9f31f&csf=1&web=1&e=wg1N9J

**Comment by lpgoldstein** [comment]
@mcharg added a sentence in the conclusion.

**Comment by Maroyafaied** [comment]
@mcharg @lpgoldstein I made minor comments, looks great.
