### ISSUE TITLE
Broken link to USEITI withdrawal letter

### ISSUE THREAD

**Issue by mcharg** [ONRR/blog-nrrd#155]
The withdrawal letter is no longer on the EITI site. We need to see if we can find this elsewhere. It's in Judy's post. https://blog-nrrd.doi.gov/product-champion/

![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/32b7bec0-2205-4349-b9fb-01c0928f3c9a)

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 if you can't a pdf then please remove the link.

**Comment by cthomasONRR** [comment]
I found a link for the US EITI withdraw letter that is functioning: https://eiti.org/sites/default/files/attachments/signed_eiti_withdraw_11-17.pdf
