### ISSUE TITLE
Broken link: EITI standard

### ISSUE THREAD

**Issue by mcharg** [ONRR/blog-nrrd#156]
In this post. https://blog-nrrd.doi.gov/making-tough-content-choices/
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/eef7a0d8-49c7-4d5f-af4c-04fca9597ac5)

**Comment by cthomasONRR** [comment]
I think this is the correct link: https://eiti.org/collections/eiti-standard
