### ISSUE TITLE
Write blog post about QA process

### ISSUE THREAD

**Issue by mcharg** [ONRR/blog-nrrd#16]

**Comment by mojobnichols** [comment]
I added a paragraph

**Comment by lpgoldstein** [comment]
@Maroyafaied This is ready for your review: https://doimspp-my.sharepoint.com/:w:/g/personal/malcolmj_mms_gov/ERxjBuQmNnpNmQYxYWULdakB7nKCx0_m0LNQcinq8XSj3Q?email=Maroya.Faied%40onrr.gov&e=NhjaGA

**Comment by Maroyafaied** [comment]
@lpgoldstein looks good, I only had minor changes.

**Comment by lpgoldstein** [comment]
@Maroyafaied Thanks! I'll create an issue to publish the blog next sprint.
