### ISSUE TITLE
Write blog post about accessibility testing on onrr.gov

### ISSUE THREAD

**Issue by mcharg** [ONRR/blog-nrrd#163]

**Comment by cthomasONRR** [comment]
Link to draft: https://doimspp-my.sharepoint.com/:w:/r/personal/thomasc_mms_gov/Documents/onrr.gov%20accessibility%20testing%20-%20blog%20post.docx?d=wcfe50cb56cc34b8eb204d1327e42bbb0&csf=1&web=1&e=KaMwC4

**Comment by cthomasONRR** [comment]
@Maroyafaied @lpgoldstein 

This first draft is ready for review: https://doimspp-my.sharepoint.com/:w:/r/personal/thomasc_mms_gov/Documents/onrr.gov%20accessibility%20testing%20-%20blog%20post.docx?d=wcfe50cb56cc34b8eb204d1327e42bbb0&csf=1&web=1&e=KaMwC4

I'd like for you to review it first, then I plan to send it to Sam to see if he wants to add in a quote.

Thanks!

**Comment by lpgoldstein** [comment]
@cthomasONRR somehow you've made this whole process seem very easy. This blog post is going to make it a lot easier for other's to test their own websites.

**Comment by cthomasONRR** [comment]
@lpgoldstein Thanks!! I addressed your comments in the Word Doc

**Comment by Maroyafaied** [comment]
@cthomasONRR Great blog! I've added comments.

**Comment by cthomasONRR** [comment]
@Maroyafaied I addressed your comments. Please let me know if my changes are ok, then I'll clean up the doc and send it to Sam. Thanks!

**Comment by cthomasONRR** [comment]
I emailed the blog doc to Sam to see if he'd like to add in a quote.

**Comment by cthomasONRR** [comment]
I created issue #180 to follow up with Sam. I will close this issue since the blog is written and reviewed.
