### ISSUE TITLE
Blog post about redoing the user types

### ISSUE THREAD

**Issue by mcharg** [ONRR/blog-nrrd#164]

**Comment by mcharg** [comment]
@Maroyafaied @lpgoldstein @cthomasONRR I started a rough draft that you can refine when you have time.
https://doimspp.sharepoint.com/:w:/r/sites/NRRD/Shared%20Documents/General/Blog/In%20Progress/User%20Types.docx?d=w1107bc8a050b41bf9660f54ac34337ae&csf=1&web=1&e=HnbIex

**Comment by cthomasONRR** [comment]
@mcharg Thanks!!!

**Comment by cthomasONRR** [comment]
@lpgoldstein @Maroyafaied I added my portion of content to the Word document. There are note callouts for where you should add in your content. Thanks!

**Comment by lpgoldstein** [comment]
@cthomasONRR and @Maroyafaied I added mine. @Maroyafaied I'll put this into markdown when we finish writing. No hurry as we already have other blog posts ready to go.

**Comment by Maroyafaied** [comment]
@lpgoldstein @cthomasONRR I finally found the time to write for my sections! @mcharg I added screenshots incase you'd like to review. 

![image](https://user-images.githubusercontent.com/40175688/184657005-5eb827fa-649d-487b-b847-bc456367d701.png)

![image](https://user-images.githubusercontent.com/40175688/184656899-0f6e57f9-ae93-4192-9cc7-5b6913d49f7c.png)

**Comment by cthomasONRR** [comment]
@maroyafaied Great!!! I found 2 images that I think need some additional explanation from you. I tagged you in the comments for them.

**Comment by cthomasONRR** [comment]
@maroyafaied Great!!! I found 2 images that I think need some additional explanation from you. I tagged you in the comments for them.

**Comment by Maroyafaied** [comment]
@cthomasONRR Thanks, I addressed your comments. Please review.

**Comment by cthomasONRR** [comment]
@Maroyafaied Looks great! Thanks!

**Comment by Maroyafaied** [comment]
will close this and make a new issue to put in markdown and publish.

**Comment by shannonmcharg** [comment]
Looks good.
