### ISSUE TITLE
Write blog post on onboarding process

### ISSUE THREAD

**Issue by mcharg** [ONRR/blog-nrrd#17]

**Comment by mcharg** [comment]
Here's a draft.
https://teams.microsoft.com/l/file/6ED5F153-F8EC-421B-A636-31257594EA6B?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=docx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FBlog%2Fonrr_blog_post_onboarding.docx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a

@lpgoldstein @jennmalcolm Do you want to review?

**Comment by jennmalcolm** [comment]
Yes I will review

**Comment by lpgoldstein** [comment]
l love gaining a new perspective on our team. I just had a few comments. Thanks!

**Comment by jennmalcolm** [comment]
I added my comments as well. Thanks.

**Comment by jennmalcolm** [comment]
continue in #23
