### ISSUE TITLE
June and July Blog Analytics 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/blog-nrrd#175]

**Comment by cthomasONRR** [comment]
@Maroyafaied 

July analytics are up on the Blog wiki: https://github.com/ONRR/blog-nrrd/wiki/Analytics
You can use this [linked](https://doimspp-my.sharepoint.com/:x:/r/personal/thomasc_mms_gov/Documents/[Blog_Analytics_July22.xlsx](https://doimspp-my.sharepoint.com/:x:/r/personal/thomasc_mms_gov/Documents/Blog_Analytics_July22.xlsx?d=wec9237e286ab4e44b50ea7e070a3f905&csf=1&web=1&e=JTqe0T)?d=wec9237e286ab4e44b50ea7e070a3f905&csf=1&web=1&e=JTqe0T) excel sheet to review.

**Comment by Maroyafaied** [comment]
@cthomasONRR I'm not able to access the spreadsheet

**Comment by cthomasONRR** [comment]
@Maroyafaied Thought I already shared it with you. You should have access now and here's the [link](https://doimspp-my.sharepoint.com/:x:/r/personal/thomasc_mms_gov/Documents/CLT%20Analytics/[Blog_Analytics_July22.xlsx](https://doimspp-my.sharepoint.com/:x:/r/personal/thomasc_mms_gov/Documents/CLT%20Analytics/Blog_Analytics_July22.xlsx?d=wec9237e286ab4e44b50ea7e070a3f905&csf=1&web=1&e=XllAhe)?d=wec9237e286ab4e44b50ea7e070a3f905&csf=1&web=1&e=XllAhe) again (I moved the file location so not sure if that messed up the link).

**Comment by Maroyafaied** [comment]
@cthomasONRR looks great, everything matches! Thanks.
