### ISSUE TITLE
blog analytics

### ISSUE THREAD

**Issue by cthomasONRR** [ONRR/blog-nrrd#179]

**Comment by cthomasONRR** [comment]
@lpgoldstein 

Blog analytics are ready for your review: https://github.com/ONRR/blog-nrrd/wiki/Analytics

Excel for reviewing: https://doimspp.sharepoint.com/:x:/r/sites/NRRD/_layouts/15/Doc.aspx?sourcedoc=%7B480D1A94-EAD7-47BF-9841-64D5D1C1A981%7D&file=Blog_Analytics.xlsx&action=default&mobileredirect=true

Thanks!

**Comment by lpgoldstein** [comment]
@cthomasONRR looks good
