### ISSUE TITLE
Consider replacing ampersand (&) in blog title

### ISSUE THREAD

**Issue by brentryanjohnson** [ONRR/blog-nrrd#181]
I've noticed the ampersand in `Open data, design, & development at the U.S. Department of the Interior` is printed as an HTML entity in certain contexts.

![Link test that reads Measuring and Justifying the Government Experience Open data, design, &amp; development at the Department of the Interior](https://user-images.githubusercontent.com/32855580/186525043-5816b1b5-4fa7-4243-8246-d845465c1a46.png)

Given the `&` appears to be part of the official team name, I opted to open an issue instead of a pull request. Just wanted to flag it!

**Comment by Maroyafaied** [comment]
@lpgoldstein will look into this

**Comment by lpgoldstein** [comment]
Just waiting to hear back from Ryan but will close this issue. It only seems to be an issue with the listserv emails
