### ISSUE TITLE
Write blog post about tree testing 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/blog-nrrd#29]

**Comment by lpgoldstein** [comment]
@Maroyafaied This is ready for your review https://doimspp-my.sharepoint.com/:w:/g/personal/goldstel_mms_gov/EUiinw5Y-1VCgGETB7EP3RYBWKfUbP_yxNBBgUs-adlptQ?email=Maroya.Faied%40onrr.gov&e=gJqOFt

**Comment by Maroyafaied** [comment]
@lpgoldstein I reviewed an added comments.
