### ISSUE TITLE
Write a review process when writing blogs

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/blog-nrrd#38]
Include things like checking content grade levels

**Comment by lpgoldstein** [comment]
@Maroyafaied I pulled down what was on the wiki before related to writing blog posts and started making some edits. Let's discuss at catchup on Monday if you are out tomorrow. I'd like to go in a slightly different direction than our current guidance if that makes sense to you after reading my comments. https://doimspp-my.sharepoint.com/:w:/g/personal/goldstel_mms_gov/ERxgbV1fQG5On8XGp_eVY_kBE4EGaDRm7l9V_19UlDPtaQ?email=Maroya.Faied%40onrr.gov&e=xuScgN

**Comment by lpgoldstein** [comment]
@Maroyafaied I updated the nrrd wiki that has the comprehensive blog publishing page. I also copied over the page to the blog repo. https://github.com/ONRR/blog-nrrd/wiki/Publishing-a-blog-post-(a-to-z)

Here is the new simple page as well. 
https://github.com/ONRR/blog-nrrd/wiki/Blog-writing-for-new-authors

**Comment by Maroyafaied** [comment]
@lpgoldstein This looks great!

**Comment by mcharg** [comment]
@lpgoldstein Found a line that's no longer relevant.
![image](https://user-images.githubusercontent.com/38465926/105854608-17538180-5fb5-11eb-9acd-4a4f2bf6314a.png)
