### ISSUE TITLE
Write blog post on trends design studio

### ISSUE THREAD

**Issue by mcharg** [ONRR/blog-nrrd#42]
Sarah started a blog post.

**Comment by mcharg** [comment]
@Maroyafaied @lpgoldstein This is ready to review. https://teams.microsoft.com/l/file/CE9B534F-F8D9-4BF3-8837-7EB8827A55B9?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=docx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FBlog%2Fonrr_blog_post_design_studio_draft_2.docx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a

**Comment by Maroyafaied** [comment]
@mcharg @arcasarana I've added my comments. Thanks

**Comment by lpgoldstein** [comment]
@arcasarana @mcharg I've added comments as well.
