### ISSUE TITLE
Blog post - retrospective

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/blog-nrrd#46]
on experience, what I've learned that I'll take to next job

**Comment by jennmalcolm** [comment]
@Maroyafaied @lpgoldstein @mcharg I have a draft of my blog ready for your review. I will put it into MDX in a branch tomorrow, so if any of you have a chance to give me feedback today, I'd appreciate it. Thanks.

https://doimspp-my.sharepoint.com/:w:/g/personal/malcolmj_mms_gov/EWapYI2W_j1Pm6O1TTXdoT8BMbMlcAzNxI_fUDr9Wx2hKQ?e=18jt0j

**Comment by Maroyafaied** [comment]
@jennmalcolm wow, it's really good! I just read it but I was too into it to catch any mistakes, I'll re read it again! but great job, it's a great read!

**Comment by mcharg** [comment]
@jennmalcolm Looks good.  I made some comments and edits.

**Comment by lpgoldstein** [comment]
@jennmalcolm This looks great on first pass. Will read again this afternoon too. We should share on onrresource when done to remind people why we all do what we do. Also keep in mind when we revisit product statement and how we work - I really like your verbiage about how people are the solution.
