### ISSUE TITLE
Write contacts blog post

### ISSUE THREAD

**Issue by mcharg** [ONRR/blog-nrrd#59]

**Comment by mcharg** [comment]
@Maroyafaied This is ready for you to review.
https://teams.microsoft.com/l/file/70019E81-5ED2-4B93-9D9C-650895432B86?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=docx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FBlog%2FBlog%20Post_%20Contacts.docx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a

**Comment by mcharg** [comment]
@Maroyafaied Brandi made updates to address our comments.

@CM805 Can you please review, since you weren't part of the design process and have an outside perspective?
https://teams.microsoft.com/l/file/70019E81-5ED2-4B93-9D9C-650895432B86?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=docx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FBlog%2FBlog%20Post_%20Contacts.docx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a

**Comment by CM805** [comment]
I made some grammatical edits and wording changes for readability.

**Comment by mcharg** [comment]
Created #69 for @daniel-coleman-1 to put the blog post into markdown.
