### ISSUE TITLE
Blog post about reviewing wireframes with stakeholders

### ISSUE THREAD

**Issue by mcharg** [ONRR/blog-nrrd#61]

**Comment by mcharg** [comment]
This is ready to review. @Maroyafaied @daniel-coleman-1 Can you please take a look?
https://doimspp-my.sharepoint.com/:w:/r/personal/mchargs_mms_gov/Documents/NRRD%20Portal/Outreach/Blog/WireframeReviews.docx?d=wd502db3d69544368825fe1f4c58735e7&csf=1&web=1&e=hTHi4V

**Comment by daniel-coleman-1** [comment]
I really liked it! Very minimal notes are attached.

https://doimspp-my.sharepoint.com/:w:/r/personal/mchargs_mms_gov/_layouts/15/Doc.aspx?sourcedoc=%7Bdb474b68-10e9-4227-b4fb-8b9c796554ab%7D&action=edit&wdPreviousSession=89df289c-ba7a-44be-ae8f-85a04e3acdd5

**Comment by Maroyafaied** [comment]
@mcharg very good, I only had one comment. Thanks
