### ISSUE TITLE
Error message when clicking on "older" (after page 2)

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/blog-nrrd#62]

**Comment by mcharg** [comment]
@cm805 Did you say you added some screenshots to this issue?  If so, you may not have submitted the comment.

**Comment by CM805** [comment]
![image](https://user-images.githubusercontent.com/83783622/118150268-97202300-b3cf-11eb-84c2-d3ddba07c319.png)

Once you are on page 2 click "older"

![image](https://user-images.githubusercontent.com/83783622/118150952-5a086080-b3d0-11eb-825d-c683e6f2962f.png)

**Comment by mcharg** [comment]
@jlouis-onrr @mojobnichols I took a look at this and it's not something I could figure out, so we need developer help.
