### ISSUE TITLE
Homepage blog post

### ISSUE THREAD

**Issue by mcharg** [ONRR/blog-nrrd#64]
Why we decided to redesign it again.

Follow-up from first blog post on the homepage.

https://blog-nrrd.doi.gov/homepage-revamp/

**Comment by arcasarana** [comment]
Here's the link to the blog post. I think it still needs some editing.

[https://teams.microsoft.com/l/message/19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype/1623932538084?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a&parentMessageId=1623932538084&teamName=NRRD&channelName=General&createdTime=1623932538084]

**Comment by mcharg** [comment]
@arcasarana @branic18 I took a look and added in comments.

@Maroyafaied Do you want to review, as well?

**Comment by Maroyafaied** [comment]
@arcasarana @branic18  I added my comments.

**Comment by mcharg** [comment]
@arcasarana Will try to get this done by EOD tomorrow.

**Comment by arcasarana** [comment]
[Usability Study_ Homepage Graphic.docx](https://github.com/ONRR/blog-nrrd/files/6848411/Usability.Study_.Homepage.Graphic.docx)

**Comment by mcharg** [comment]
@arcasarana I'll create a GitHub version of the plan and findings that you can link to.

**Comment by mcharg** [comment]
@arcasarana 
Plan & Guide: https://github.com/ONRR/research/blob/master/nrrd-research/38_HomepageGraphic/Homepage%20Graphic%20Plan%20and%20Guide.md

Findings: https://github.com/ONRR/research/blob/master/nrrd-research/38_HomepageGraphic/Consolidated%20Findings%20for%20GitHub.xlsx?raw=true

**Comment by mcharg** [comment]
@arcasarana It's looking good.  I made a few additional edits and comments.

@Maroyafaied Do you want to review?  Should we have @CM805 review when she's back next week?

**Comment by Maroyafaied** [comment]
@mcharg I reviewed and made a few changes, please ask @CM805 to review next week as well. Thanks

**Comment by CM805** [comment]
I reviewed and made a few grammatical changes
