### ISSUE TITLE
Add analytics tags to new blog site

### ISSUE THREAD

**Issue by mcharg** [ONRR/blog-nrrd#7]

**Comment by jlouis-onrr** [comment]
@mcharg, started looking at this one.  It appears their currently is GA tag in place, however when searching for the GA id across our GA account nothing is coming up.  Perhaps this was under a different account at some point that no longer exists?

**Comment by jlouis-onrr** [comment]
@mcharg, also looks like i dont have access or permissions to this branch.  gonna need that in order to push out changes.

**Comment by jlouis-onrr** [comment]
@mcharg, you should now be seeing the GA firing from the blog dev site.

**Comment by mcharg** [comment]
It is showing up.
![image](https://user-images.githubusercontent.com/38465926/89914155-9a794a80-dbc2-11ea-92da-e804e6b5db33.png)
