### ISSUE TITLE
Write guide for writing and approving blog posts

### ISSUE THREAD

**Issue by daniel-coleman-1** [ONRR/blog-nrrd#71]

**Comment by Maroyafaied** [comment]
include checking reading level and alt text.

**Comment by daniel-coleman-1** [comment]
[Blog Post Approval Guide.docx](https://github.com/ONRR/blog-nrrd/files/7017955/Blog.Post.Approval.Guide.docx)

Just a draft to get me away from Axure

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 Thanks for working on this, can you put this in our shared team folder and share the link so I can review. Thanks

**Comment by daniel-coleman-1** [comment]
https://doimspp-my.sharepoint.com/:w:/g/personal/mchargs_mms_gov/ETLdjnwdWr9Doq-VMYX8c-oBTI2bOXDUgC0xzufEFOWeYA?e=WoSDjC

I think this is an issue for next sprint

**Comment by mcharg** [comment]
Check 18F content guide with info about blogs.

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 I just found a wiki page that our previous content strategist wrote on publishing blog posts, when working this issue please look into what's already been written and what else we need to add. @mcharg do you know why this page was archived? How can I un archive it and move it the NRRD wiki? Thanks https://github.com/ONRR/doi-extractives-data/wiki/Publishing-a-blog-post

**Comment by mcharg** [comment]
@Maroyafaied We moved it to the blog wiki. https://github.com/ONRR/blog-nrrd/wiki/Publishing-a-blog-post-(a-to-z)

**Comment by Maroyafaied** [comment]
Add editing and approval process to wiki

**Comment by Maroyafaied** [comment]
@mcharg review written process.

**Comment by mcharg** [comment]
@daniel-coleman-1 How is this going to fit in with the current guidance?  Will it be part of the team review step on this page? 
https://github.com/ONRR/blog-nrrd/wiki/Blog-writing-for-new-authors

I'm already a bit confused about the difference between that page and this one.  Not sure how a third fits in.
https://github.com/ONRR/blog-nrrd/wiki/Publishing-a-blog-post-(a-to-z)

Can you please clarify the content strategy for the three pages?

**Comment by mcharg** [comment]
@daniel-coleman-1 I added comments to the doc.  This is quite a bit different from how I review a blog post.  @Maroyafaied you should review, as well, so we can make sure we have agreement on the role of the reviewer.

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 The process has been that we ask the content strategist and other team members to review twice in one sprint; once the blog is in a shard doc and once it's in a PR which are steps 7 and 8 in this [ current guidance](https://github.com/ONRR/blog-nrrd/wiki/Blog-writing-for-new-authors). I recommend adding checklists under these steps but I'm open to hear other strategies.  Below is examples of my recommendation, please let me know your thoughts/ strategy. 

For example, under step 7 (blog in word doc) the reviewers should ensure:
- Blog follows NRRD content guide (punctuations, capitalizations, etc)
- Run blog through hemmingway to check reading level is grade 10 or lower
For example under step 8 (blog in markdown and in a PR) the reviewers should:
- Check again for proper grammer and punctuation
- Ensure all images show up with alt text
- Ensure links go to correct destination

**Comment by mcharg** [comment]
@daniel-coleman-1 I agree with Maroya's suggestion.

**Comment by Maroyafaied** [comment]
@cthomasONRR @lpgoldstein @mcharg please review the updated instructions based on the content tracking sheet. Once you are done with your review , I can use it for issue #1246 since I just added that page and @cthomasONRR can test it out again when she adds pages. https://doimspp.sharepoint.com/sites/NRRD/_layouts/15/doc.aspx?sourcedoc={e1a9e465-d8df-40bc-a745-1c5c891ca07a}&action=edit

**Comment by mcharg** [comment]
@Maroyafaied Did you mean to put this comment on #351 (onrr.gov)?

**Comment by Maroyafaied** [comment]
@mcharg Yes, I copied it over to the right issue.

**Comment by daniel-coleman-1** [comment]
Thanks for the edits @mcharg, I've incorporated them into the A to Z guide:
https://github.com/ONRR/blog-nrrd/wiki/Publishing-a-blog-post-(a-to-z)

Added checklist to Step 6:
![Screenshot 2022-01-21 135235](https://user-images.githubusercontent.com/83892362/150599169-a896cb0a-f3a0-47f3-8cd7-26524299cb6e.png)


And inserted a new Step 8 for markdown editing, which raised the total amount of steps from 11 to 12:
![Screenshot 2022-01-21 134934](https://user-images.githubusercontent.com/83892362/150599178-39c78391-4703-4727-9f73-edd81373b980.png)

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 @mcharg this is good to close. Thanks
