### ISSUE TITLE
Write blog post about transitioning into the manager role

### ISSUE THREAD

**Issue by mcharg** [ONRR/blog-nrrd#80]

**Comment by Maroyafaied** [comment]
Here is my draft, feel free to edit and give feedback. @daniel-coleman-1 @mcharg @cvojslavek https://teams.microsoft.com/l/file/718889AC-D36D-4A71-98F1-0292C10671E5?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=docx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FBlog%2FTransition%20to%20management.docx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a

**Comment by mcharg** [comment]
@Maroyafaied Looks good!  I made a few edits.

**Comment by Maroyafaied** [comment]
@mcharg Thanks, I changed some of the titles to the paragraph, feel free to give suggestions on that. @lpgoldstein @cthomasONRR feel free to review as well. Thanks

**Comment by mcharg** [comment]
@Maroyafaied I just tweaked them to all use the same verb construction.

**Comment by mcharg** [comment]
@Maroyafaied One thing you might want to add is a strong closing statement after the list of advice.

**Comment by Maroyafaied** [comment]
@mcharg Thanks, that's a good point. I'll come up with something.

**Comment by lpgoldstein** [comment]
@Maroyafaied You make it all sound so easy despite having a challenging and successful year at the same time. I just made a few grammatical edits. The new manager list is helpful for everyone too.

**Comment by daniel-coleman-1** [comment]
I think this is two blog posts. "Stepping out of my comfort zone" and "Eight Pieces of Advice for New Managers"

I think @Maroyafaied you could end the "Getting and giving feedback and support" with a paragraph about how you learned and grew in the role, adapted and made changes in perspective, etc, and have an eight-piece list of advice for a new manager in the next post (shameless plug).  Essentially the closing paragraph but tied in with a plug for the list.

If in "My advice to a new manager" you gave two or three short anecdotal examples per bullet point you'd probably add 300-500 words. That makes the section sizable enough for its own post, easily digestible and in list format.

@lpgoldstein @cthomasONRR @mcharg what do you think?

**Comment by Maroyafaied** [comment]
@daniel-coleman-1 Thanks for your suggestion, I probably won't have time to write a 2nd blog post so I will work next week on adding a paragraph to transition into the advice section better and a paragraph as a closing statement.

**Comment by Maroyafaied** [comment]
I added 2 paragraphs if anyone wants to review. Thanks

**Comment by lpgoldstein** [comment]
@Maroyafaied I just reviewed and only made grammar/spelling/syntax edits. I loved getting insight into your past year.

**Comment by daniel-coleman-1** [comment]
@Maroyafaied made a few edits.  Looks good!

**Comment by mcharg** [comment]
@Maroyafaied Looks good.  I dropped the new paragraphs into Hemingway and clarified a few sentences that were coming back as very hard to read.

**Comment by Maroyafaied** [comment]
Closing this and will create a PR.
