### ISSUE TITLE
Write blog post about cross training experience - Christa 

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/blog-nrrd#84]

**Comment by CM805** [comment]
Emailed draft to @Maroyafaied and @mcharg

**Comment by CM805** [comment]
[McCurdy Blog Post.docx](https://github.com/ONRR/blog-nrrd/files/7086722/McCurdy.Blog.Post.docx)

Emailed attached draft to @mcharg and @Maroyafaied

**Comment by Maroyafaied** [comment]
@CM805 I loved it, I enjoyed reading your experience from your prespectiveand how you focused on our agile project management.  I added some comments. https://doimspp-my.sharepoint.com/:w:/r/personal/mchargs_mms_gov/_layouts/15/Doc.aspx?sourcedoc=%7B7D73E9BE-24F9-4A56-9CFB-D2A72B95364D%7D&file=McCurdy%20Blog%20Post.docx&action=default&mobileredirect=true

**Comment by mcharg** [comment]
@CM805 I enjoyed reading it, as well.  I added comments.

**Comment by CM805** [comment]
Thanks for the review.  I addressed the issues and suggestions.  Please take another look and let me know any additional thoughts you have!

**Comment by mcharg** [comment]
@CM805 Took another look and looks good!

**Comment by Maroyafaied** [comment]
@CM805 is this ready for @daniel-coleman-1 to put into markdown?
