### ISSUE TITLE
Rename the blog

### ISSUE THREAD

**Issue by mcharg** [ONRR/blog-nrrd#90]
To Open Data, Design, & Development at the U.S. Department of the Interior.

**Comment by mcharg** [comment]
Updated in Meshan's blog post PR.
https://dev-blog-nrrd.app.cloud.gov/

@Maroyafaied Do you want to review?  Should we use the purple bison?

**Comment by Maroyafaied** [comment]
@mcharg it looks good, I think the blue bison is fine since it's a part of the NRRD site.
