### ISSUE TITLE
Update Meshan's blog post with new team name

### ISSUE THREAD

**Issue by mcharg** [ONRR/blog-nrrd#91]

**Comment by mcharg** [comment]
@Maroyafaied @cthomasONRR @lpgoldstein This is updated in @meshanw's blog post PR if one of you wants to review.
https://dev-blog-nrrd.app.cloud.gov/Cross-training/

**Comment by cthomasONRR** [comment]
@mcharg Looks good, but this sentence doesn't really make sense anymore:
"As time went on, I began to hear little chatter of what others thought they did like “They work with GSA” “They publish/display data to NRRD (the Natural Resources Revenue Data website), hence their name, Duh! – ODDD team.”

**Comment by mcharg** [comment]
@cthomasONRR Good point.  @meshanw Do you want to rewrite that sentence?

**Comment by mcharg** [comment]
@meshanw @cthomasONRR Does this work?

"As time went on, I began to hear little chatter of what others thought they did like “They work with GSA” “They publish/display data to NRRD (the Natural Resources Revenue Data website), hence their name, Duh! – Data Display team.” (Note: The team was formerly called the Data Display team."

**Comment by cthomasONRR** [comment]
@mcharg that works for me!

**Comment by mcharg** [comment]
Updated with the above language.
