### ISSUE TITLE
Republish sketchy version of wireframes to a new url and update link in Stakeholder Buy-in post

### ISSUE THREAD

**Issue by mcharg** [ONRR/blog-nrrd#92]
It won't make sense for people to see the visual designed version that's currently linked.

**Comment by mcharg** [comment]
Updated in Meshan's blog post PR.

@cthomasONRR or @lpgoldstein does one of you want to review?
https://dev-blog-nrrd.app.cloud.gov/stakeholders/

**Comment by cthomasONRR** [comment]
@mcharg what needs to be reviewed at https://dev-blog-nrrd.app.cloud.gov/stakeholders/? Which link was updated?

**Comment by mcharg** [comment]
@cthomasONRR The two links to the wireframes should be back to being sketchy instead of the visually designed version.

**Comment by cthomasONRR** [comment]
@mcharg OK checked the post, and those 'new' wireframe links are back to being sketchy :) Looks good to me!

**Comment by mcharg** [comment]
@cthomasONRR Thanks!
