### ISSUE TITLE
Add ability to request a blog topic

### ISSUE THREAD

**Issue by mcharg** [ONRR/blog-nrrd#93]

**Comment by mcharg** [comment]
@Maroyafaied @lpgoldstein @cthomasONRR Does this work?
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/03e47afa-175a-47f0-b283-ccaa42a7acc9)

**Comment by lpgoldstein** [comment]
@mcharg yes!

**Comment by Maroyafaied** [comment]
@mcharg Looks great. Thanks

**Comment by cthomasONRR** [comment]
@mcharg Looks good!
