### ISSUE TITLE
FY21 blog analytics

### ISSUE THREAD

**Issue by mcharg** [ONRR/blog-nrrd#95]

**Comment by mcharg** [comment]
Requested unsampled report that should run over the weekend.

**Comment by mcharg** [comment]
@lpgoldstein Here's an unsampled report with page views for the fiscal year.  Do you need anything more than that?
https://doimspp-my.sharepoint.com/:x:/r/personal/mchargs_mms_gov/Documents/NRRD%20Portal/NRRD%20Metrics/Analytics/Blog%20Analytics/FY21/Analytics%20DOI%20Agency%20Profile%20Blog%20Usage%20-%20FY21%2020201001-20210930.xlsx?d=wd35016b36381418786776ff649abb0f8&csf=1&web=1&e=CDB8H2

**Comment by lpgoldstein** [comment]
@mcharg This is perfect, thank you
